USE CODEGNAN; 
CREATE TABLE STUDENT_DATA (
ID INT NOT NULL,
STUDNAME VARCHAR(50) NOT NULL,
STUSUBJECT VARCHAR(10),
MARKS INT DEFAULT 0
);
INSERT INTO STUDENT_DATA VALUES (1,"CHANDANA","ENGLISH",99),(1,"CHANDANA","MATHS",80),(1,"CHANDANA","SOCIAL",70); 
INSERT INTO STUDENT_DATA VALUES (2,"CHANDU","ENGLISH",90),(2,"CHANDU","MATHS",88),(2,"CHANDU","SOCIAL",77); 
INSERT INTO STUDENT_DATA VALUES (3,"SRI","ENGLISH",99),(3,"SRI","MATHS",70),(3,"SRI","SOCIAL",60); 
INSERT INTO STUDENT_DATA VALUES (4,"ADITYA","ENGLISH",99),(4,"ADITYA","MATHS",99),(4,"ADITYA","SOCIAL",78); 
INSERT INTO STUDENT_DATA VALUES (5,"RAM","ENGLISH",99),(5,"RAM","MATHS",80),(5,"RAM","SOCIAL",70); 
INSERT INTO STUDENT_DATA VALUES (6,"SRIRAM","ENGLISH",90),(6,"SRIRAM","MATHS",80),(6,"SRIRAM","SOCIAL",90); 

SELECT SUM(ID) FROM STUDENT_DATA;

SELECT SUM(MARKS) FROM STUDENT_DATA; 

SELECT COUNT(ID) FROM STUDENT_DATA;

SELECT MAX(MARKS) FROM STUDENT_DATA;

SELECT MIN(MARKS) FROM STUDENT_DATA;

SELECT AVG(MARKS) FROM STUDENT_DATA;


-- I NEED TOTAL MARKS RECORDS FOR EACH STUDENT

SELECT ID,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID; 
SELECT ID,MARKS AS ENGLISH_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "ENGLISH"; 

TRUNCATE STUDENT_DATA; 

CREATE TABLE FINAL_MARKS (
ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(50),
STUDENT_MARKS INT
); 

SELECT * FROM FINAL_MARKS; 
INSERT INTO FINAL_MARKS SELECT ID,STUDNAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDNAME;

SELECT ID,STUDNAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDNAME HAVING TOTAL_MARKS > 150;
SELECT ID,STUDNAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDNAME HAVING TOTAL_MARKS > 150 ORDER BY TOTAL_MARKS ASC;

SELECT ID,STUDNAME,MARKS AS MATHS_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "MATHS";
SELECT ID STUDNAME,MARKS AS ENGLISH_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "ENGLISH";
SELECT ID STUDNAME,STUSUBJECT AS SOCIAL_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "SOCIAL";
SELECT ID,STUDNAME,MARKS AS SOCIAL_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "SOCIAL" ORDER BY SOCIAL_MARKS ASC;
SELECT ID,STUDNAME,MARKS AS SOCIAL_MARKS FROM STUDENT_DATA WHERE STUSUBJECT = "SOCIAL" ORDER BY SOCIAL_MARKS DESC; 


-----------------------------------------------------------------------------------------------------------------------------
DROP DATABASE CHANDANA;

