USE CODEGNAN;
CREATE TABLE STUDENT123(
ID INT,
SNAME VARCHAR(50)
);
INSERT INTO STUDENT123 VALUES (1,"KUSHI"),(2,"KUSHI1"),(3,"KUSHI2"),(4,"KUSHI3");
SELECT * FROM STUDENT123;

CREATE TABLE COURSE123(
CID INT,
CNAME VARCHAR(50)
);
INSERT INTO COURSE123 VALUES (1,"CSE"),(2,"ECE"),(1,"EEE"),(4,"ABC");
SELECT * FROM COURSE123;

DROP TABLE COURSE123;

-- INNER JOIN

SELECT ID,SNAME,CNAME 
FROM STUDENT123
INNER JOIN COURSE123 
ON STUDENT123.ID = COURSE123.CID;

-- LEFT JOIN
SELECT ID,SNAME,CNAME
FROM STUDENT123
LEFT JOIN COURSE123 
ON STUDENT123.ID = COURSE123.CID;

-- RIGHT JOIN
INSERT INTO COURSE123 VALUES (5,"SAI"),(6,"SAI1");
SELECT ID,SNAME,CNAME 
FROM STUDENT123
RIGHT JOIN COURSE123 
ON STUDENT123.ID = COURSE123.CID;

-- OUTER FULL JOIN
SELECT ID,SNAME,CNAME 
FROM STUDENT123
LEFT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID
UNION 
SELECT ID,SNAME,CNAME
FROM STUDENT123
RIGHT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- SELF JOIN
CREATE TABLE CLR (
COLOR1 VARCHAR(10),
CNAME VARCHAR(50),
COLOR2 VARCHAR(10)
);
INSERT INTO CLR VALUES ("BLUE","JOHN","RED"),("GREEN","KUSHI","BLUE"),("RED","CHANDANA","GREEN");
SELECT * FROM CLR;
SELECT B.CNAME AS SCREATE_SANTA,A.CNAME AS NAME
FROM CLR AS A,CLR AS B
WHERE A.COLOR1=B.COLOR2;


-- CROSS JOIN
CREATE TABLE CLR1 (
     COLOR1 VARCHAR (10),
     CNAME VARCHAR (10),
     COLOR2 VARCHAR (10)
);
INSERT INTO CLR1 VALUES("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");
SELECT * FROM CLR1;
SELECT A.CNAME AS NAME,B.CNAME AS SECRECT_SANTA
FROM CLR1 AS A, CLR AS B
WHERE A.COLOR1=B.COLOR2;
CREATE TABLE HAIRSTYLE(
     NAMEE VARCHAR(50)
);
INSERT INTO HAIRSTYLE VALUES ("STRAIGHT"),("CURLY");
SELECT * FROM HAIRSTYLE;
CREATE TABLE HAIRTYPE(
     UNAME VARCHAR(3)
);
INSERT INTO HAIRTYPE VALUES ("A"),("B"),("C"),("D");
SELECT * FROM HAIRTYPE;
SELECT  UNAME,NAMEE FROM HAIRSTYLE 
CROSS JOIN 
HAIRTYPE
LIMIT 5;



